### ISSUE TITLE
Update Desain

### ISSUE THREAD

**Issue by gpramasita** [gpramasita/AplikasiKebugaran#2]
@Firmanfilkom upload gambar desain disini, terus penjelasan gambar dan link gambarnya ambil dari sini

**Comment by Firmanfilkom** [comment]
[Penjelasan Desain Projek MKPL.docx](https://github.com/gpramasita/AplikasiKebugaran/files/1534882/Penjelasan.Desain.Projek.MKPL.docx)
![layar_awal copy](https://user-images.githubusercontent.com/34299584/33658415-38a96efa-daaf-11e7-8d18-17d72e3d6c52.jpg)
![layar_bmi_minor copy](https://user-images.githubusercontent.com/34299584/33658434-4978985a-daaf-11e7-837e-9869fe06a577.jpg)
![layar_bmi copy](https://user-images.githubusercontent.com/34299584/33658435-49c3aa98-daaf-11e7-9910-c250bcd51bba.jpg)
![layar_solusi_bmi copy](https://user-images.githubusercontent.com/34299584/33658447-55b91a18-daaf-11e7-9c41-04bf2717692b.jpg)
![layar_saran_kebugaran copy](https://user-images.githubusercontent.com/34299584/33658465-60c238ae-daaf-11e7-86b3-5f5e9c6ee75c.jpg)
![layar_kebugaran copy](https://user-images.githubusercontent.com/34299584/33658466-61076b0e-daaf-11e7-82b8-8a514da34b23.jpg)

**Comment by chipunk** [comment]
untuk minor nya?

**Comment by Firmanfilkom** [comment]
Udah aku jelasin juga di penjelasan desain ada change minor dengan tambahan gender pada bagian BMI

**Comment by Firmanfilkom** [comment]
Desain V1.1
![layar_awal copy](https://user-images.githubusercontent.com/34299584/33665627-2c08bad2-daca-11e7-97e7-1335ef514ac0.jpg)
![layar_bmi copy](https://user-images.githubusercontent.com/34299584/33665638-35c7e066-daca-11e7-9e7b-4a21402e1975.jpg)
[Penjelasan Desain Projek MKPL.docx](https://github.com/gpramasita/AplikasiKebugaran/files/1535439/Penjelasan.Desain.Projek.MKPL.docx)
Desain V1.2 Change minor => Layout BMI
![layar_bmi_minor copy](https://user-images.githubusercontent.com/34299584/33665687-5e045f5a-daca-11e7-96cf-0ca60b603b3b.jpg)
![layar_solusi_bmi copy](https://user-images.githubusercontent.com/34299584/33665695-63158618-daca-11e7-96f0-57c293f92a56.jpg)

**Comment by Firmanfilkom** [comment]
Desain V2.0
[Penjelasan Desain Projek MKPL.docx](https://github.com/gpramasita/AplikasiKebugaran/files/1536393/Penjelasan.Desain.Projek.MKPL.docx)
![layar_awal_v2 copy](https://user-images.githubusercontent.com/34299584/33678224-b8b73b7a-daed-11e7-9cdf-3a03c021dbd1.jpg)
Desain V2.1
![layar_beratideal_new copy](https://user-images.githubusercontent.com/34299584/33678246-cf0ab4e2-daed-11e7-936b-c173f173f93e.jpg)
Desain V2.1 Change minor => gender
![layar_beratideal_v2 copy](https://user-images.githubusercontent.com/34299584/33678282-e8c6233a-daed-11e7-9454-baf1fe1af962.jpg)
Desain V2.2 Change minor => hasil beda Layout
![layar_bi_v2 copy](https://user-images.githubusercontent.com/34299584/33678342-0e40fc34-daee-11e7-9c88-1e8018cb81cf.jpg)
![layar_hasil_bi_2 copy](https://user-images.githubusercontent.com/34299584/33678344-0e8973a6-daee-11e7-99da-1d64969a2ee5.jpg)

**Comment by Firmanfilkom** [comment]
Masih harus kirim email ke bapaknya kan?

**Comment by gpramasita** [comment]
Nggak ngerti ketua kelasnya juga nggak bales, tadi kutanyain...
