### ISSUE TITLE
Update Source Code untuk Aplikasi Kebugaran

### ISSUE THREAD

**Issue by gpramasita** [gpramasita/AplikasiKebugaran#3]
@alt610

**Comment by gpramasita** [comment]
![screen shot 2017-12-06 at 6 15 31 pm](https://user-images.githubusercontent.com/24559571/33663890-37fd3bac-dac4-11e7-8aae-fa8e2683cfb3.png)

Gradle failed

**Comment by alfintrr** [comment]
coba update
